Repository falcosecurity/plugins, pull requests merged in 2021-11, with the labels that each got.

#30 Fix event source for cloudtrail plugin
  plugins/PLUGINS-REGISTRY.md
Labels: kind/documentation, dco-signoff: yes, approved, release-note-none, size/XS, lgtm, area/documentation

#29 Add better support for read_progress to c++ sdk
  sdk/cpp/falcosecurity_plugin.h
Labels: dco-signoff: yes, approved, release-note-none, lgtm, kind/cleanup, area/source-plugins, size/S

#31 Update all plugins to latest plugin-sdk-go
  plugins/cloudtrail/go.mod
  plugins/cloudtrail/go.sum
  plugins/dummy/go.mod
  plugins/dummy/go.sum
  plugins/json/go.mod
  plugins/json/go.sum
Labels: dco-signoff: yes, approved, release-note-none, lgtm, kind/cleanup, area/build, size/S

#33 update(plugins): upgrade go sdk to v0.0.0-20211125012426-11baaa45581c
  plugins/cloudtrail/go.mod
  plugins/cloudtrail/go.sum
  plugins/dummy/go.mod
  plugins/dummy/go.sum
Labels: kind/bug, dco-signoff: yes, approved, size/M, release-note-none, lgtm

#32 fix(cloudtrail): properly read init config
  plugins/cloudtrail/cloudtrail.go
Labels: kind/bug, dco-signoff: yes, approved, release-note-none, lgtm, area/source-plugins, area/extractor-plugins, size/S
