Repository falcosecurity/plugins, pull requests merged in 2021-09, with the labels that each got.

#5 Fix prow build
  build.sh
Labels: dco-signoff: yes, approved, release-note-none, size/XS, lgtm

#3 docs(README.md): notice regarding the project status
  README.md
Labels: dco-signoff: yes, approved, size/XS, lgtm

#4 docs(.github): add pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: dco-signoff: yes, approved, size/M, release-note-none, lgtm

#7 Add README for cloudwatch plugin
  plugins/cloudtrail/README.md
Labels: kind/documentation, dco-signoff: yes, approved, release-note-none, lgtm, area/documentation, size/L

#8 Don't return event numbers in plugin_next()
  plugins/dummy/dummy.go
  plugins/dummy_c/dummy.cpp
Labels: dco-signoff: yes, approved, lgtm, kind/cleanup, area/source-plugins, release-note, size/S

#9 Add a ct.error field to extract errors
  plugins/cloudtrail/README.md
  plugins/cloudtrail/cloudtrail.go
Labels: kind/feature, dco-signoff: yes, approved, size/XS, lgtm, area/source-plugins, release-note
