Repository falcosecurity/plugins, pull requests merged in 2022-01, with the labels that each got.

#45 build: moved to use plugin-sdk-cpp repository
  .gitignore
  Makefile
  plugins/dummy_c/Makefile
  sdk/cpp/README.md
  sdk/cpp/falcosecurity_plugin.h
Labels: dco-signoff: yes, approved, release-note-none, lgtm, kind/cleanup, area/build, size/XXL

#46 Cloudtrail: Fixup some field display names.
  plugins/cloudtrail/extract.go
Labels: dco-signoff: yes, approved, release-note-none, size/XS, lgtm, kind/cleanup, area/source-plugins, ok-to-test

#48 update(.github): remove release note from PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: kind/documentation, dco-signoff: yes, approved, lgtm, kind/cleanup, area/documentation, size/S

#50 chore(registry): fix spacing issues
  registry.yaml
Labels: dco-signoff: yes, approved, size/XS, lgtm, kind/cleanup, area/documentation

#51 update(.github): add registry kind in PR template and unify plugins area
  .github/PULL_REQUEST_TEMPLATE.md
Labels: kind/documentation, dco-signoff: yes, approved, size/XS, lgtm, kind/cleanup, area/documentation

#53 docs(README.md): update plugin registry table
  README.md
Labels: kind/documentation, dco-signoff: yes, approved, lgtm, area/documentation, size/S

#55 Fix off-by-one error in NextBatch
  plugins/cloudtrail/cloudtrail.go
Labels: kind/bug, dco-signoff: yes, approved, size/XS, lgtm, area/plugins

#59 fix(plugins/json): fix quoting and escaping in string-based json.value
  plugins/json/json.go
Labels: kind/bug, dco-signoff: yes, approved, lgtm, size/S, area/plugins

#60 Update desc text for ct.error (not found value)
  plugins/cloudtrail/extract.go
Labels: kind/documentation, dco-signoff: yes, approved, size/XS, lgtm, area/plugins

#61 update(plugins/cloudtrail): bump plugin version to 0.2.3
  plugins/cloudtrail/cloudtrail.go
Labels: dco-signoff: yes, approved, size/XS, lgtm, kind/cleanup, area/plugins

#62 chore(readme): updated links pointing to falco doc.
  README.md
Labels: dco-signoff: yes, approved, size/XS, lgtm, kind/cleanup, area/documentation
