Repository falcosecurity/plugins, pull requests merged in 2022-10, with the labels that each got.

#164 Update pagination function for cloudwatch logs
  shared/go/aws/cloudwatchlogs/cloudwatch.go
Labels: dco-signoff: yes, approved, size/M, lgtm, kind/cleanup

#165 update(plugins/cloudtrail): Add a region setting.
  plugins/cloudtrail/pkg/cloudtrail/aws.go
Labels: dco-signoff: yes, approved, lgtm, kind/cleanup, size/S, ok-to-test, area/plugins

#170 fix(oci-tool/output): porperly populate the map entries when reading from file
  build/oci/pkg/output/output.go
Labels: kind/bug, dco-signoff: yes, approved, size/XS, lgtm, area/registry

#174 update: temporarily remove cron job when uploading OCI artifacts
  .github/workflows/upload-oci-artifacts.yaml
Labels: dco-signoff: yes, approved, size/XS, lgtm

#176 fix cron timer
  .github/workflows/upload-oci-artifacts.yaml
Labels: dco-signoff: yes, approved, size/XS, lgtm

#177 chore: little modification to dummy_c description to test prow CI
  registry.yaml
Labels: dco-signoff: yes, approved, size/XS, lgtm, area/registry

#179 docs(README.md): update plugin registry table
  README.md
Labels: kind/documentation, dco-signoff: yes, approved, size/XS, lgtm, area/documentation

#178 fix(oci-registry: correctly set repo value for plugin artifacts
  build/registry/pkg/registry/distribution/index.go
Labels: kind/bug, dco-signoff: yes, approved, lgtm, size/S, area/registry

#180 update(registry): update registry.yaml
  registry.yaml
Labels: dco-signoff: yes, approved, size/XS, lgtm, kind/cleanup, area/registry

#181 docs(README.md): update plugin registry table
  README.md
Labels: kind/documentation, dco-signoff: yes, approved, size/XS, lgtm, area/documentation

#185 refine the GitHub miner detection rule
  plugins/github/rules/github.yaml
Labels: kind/feature, dco-signoff: yes, approved, size/XS, lgtm, area/plugins
