Repository falcosecurity/plugins, pull requests merged in 2022-08, with the labels that each got.

#140 docs(best-practices): update URL
  docs/best-practices.md
Labels: kind/documentation, dco-signoff: yes, approved, size/XS, lgtm, area/documentation

#139 Config schema title default
  docs/best-practices.md
  plugins/cloudtrail/pkg/cloudtrail/config.go
  plugins/dummy/pkg/dummy/dummy.go
  plugins/github/pkg/github/config.go
  plugins/json/pkg/json/config.go
  plugins/k8saudit/pkg/k8saudit/config.go
  plugins/okta/pkg/okta/okta.go
Labels: kind/documentation, dco-signoff: yes, approved, size/M, lgtm, kind/cleanup, area/documentation, ok-to-test, area/plugins

#131 add shared libs for AWS Session + Cloudwatch
  shared/go/aws/cloudwatchlogs/cloudwatch.go
  shared/go/aws/cloudwatchlogs/go.mod
  shared/go/aws/cloudwatchlogs/go.sum
  shared/go/aws/session/go.mod
  shared/go/aws/session/go.sum
  shared/go/aws/session/session.go
Labels: dco-signoff: yes, approved, lgtm, kind/design, size/L, area/plugins

#141 feature(plugins/k8saudit/rules): Add ka.target.resource
  plugins/k8saudit/rules/k8s_audit_rules.yaml
Labels: kind/feature, dco-signoff: yes, approved, size/M, lgtm, area/plugins

#142 chore(plugins/github): update readme
  plugins/github/README.md
Labels: dco-signoff: yes, approved, size/XS, lgtm, kind/cleanup, area/documentation
