Repository falcosecurity/plugins, pull requests merged in 2022-02, with the labels that each got.

#64 fix(registry): remove uniqueness constraint on source name
  README.md
  build/registry/check.go
Labels: dco-signoff: yes, approved, size/XS, lgtm, kind/design, area/documentation, area/registry

#65 fix(plugin/cloudtrail): manage cloudtrail empty file.
  plugins/cloudtrail/source.go
Labels: kind/bug, dco-signoff: yes, approved, size/XS, lgtm, ok-to-test, area/plugins

#66 update(OWNERS): add jasondellaluce
  OWNERS
Labels: kind/documentation, dco-signoff: yes, approved, size/XS, lgtm, area/documentation

#69 register new plugin for Docker
  registry.yaml
Labels: kind/feature, dco-signoff: yes, approved, size/XS, lgtm, area/plugins

#74 docs(README.md): update plugin registry table
  README.md
Labels: kind/documentation, dco-signoff: yes, approved, size/XS, lgtm, area/documentation

#73 register new plugin for Seccomp Agent
  registry.yaml
Labels: kind/feature, dco-signoff: yes, approved, size/XS, lgtm, ok-to-test, area/plugins

#75 docs(README.md): update plugin registry table
  README.md
Labels: kind/documentation, dco-signoff: yes, approved, size/XS, lgtm, area/documentation
