Repository falcosecurity/plugins, pull requests merged in 2023-06, with the labels that each got.

#291 fix(ci/release.yaml): fix release version check on publish
  .github/workflows/release.yml
Labels: kind/bug, dco-signoff: yes, approved, size/XS, lgtm, area/build

#292 update(ci/release.yaml): avoid cancelling concurrent release jobs
  .github/workflows/release.yml
Labels: kind/bug, dco-signoff: yes, approved, size/XS, lgtm, kind/cleanup, area/build

#293 update(ci/release.yaml): setup per-plugin release concurrency
  .github/workflows/release.yml
Labels: dco-signoff: yes, approved, size/XS, lgtm, kind/cleanup, area/build

#294 docs(README.md): add scope and status badges
  README.md
Labels: kind/documentation, dco-signoff: yes, approved, size/XS, lgtm

#298 update(plugins/cloudtrail): Increase our default S3 concurrency
  plugins/cloudtrail/pkg/cloudtrail/config.go
Labels: dco-signoff: yes, approved, size/XS, lgtm, kind/cleanup, area/plugins
