Repository falcosecurity/plugins, pull requests merged in 2023-08, with the labels that each got.

#317 Add syslogsrv plugin
  registry.yaml
Labels: kind/feature, dco-signoff: yes, approved, lgtm, size/S, area/plugins

#320 vote: add Issif as approvers for k8saudit-eks plugin
  plugins/k8saudit-eks/OWNERS
Labels: kind/documentation, dco-signoff: yes, approved, size/XS, lgtm, area/plugins

#321 docs(README.md): update plugin registry table
  README.md
Labels: kind/documentation, dco-signoff: yes, approved, size/XS, lgtm, area/documentation

#328 fix(ci): validate in container to satisfy glibc requirements
  .github/workflows/reusable_validate_plugins.yaml
Labels: kind/bug, dco-signoff: yes, approved, size/XS, lgtm, area/build

#330 fix(ci): solve validation workflow issues
  .github/workflows/reusable_validate_plugins.yaml
  plugins/gcpaudit/rules/gcp_auditlog_rules.yaml
Labels: kind/bug, dco-signoff: yes, approved, lgtm, area/build, size/S

#331 fix(ci): solve VCS stamping issues in validation workflow
  .github/workflows/reusable_validate_plugins.yaml
Labels: kind/bug, dco-signoff: yes, approved, size/XS, lgtm, kind/cleanup, area/build
