Repository falcosecurity/plugins, pull requests merged in 2023-03, with the labels that each got.

#247 feature(plugins/okta): add okta.org as available field
  plugins/okta/pkg/okta/okta.go
Labels: dco-signoff: yes, approved, size/XS, lgtm, ok-to-test

#248 feature(plugins/okta): make api token and organization field optional
  plugins/okta/pkg/okta/okta.go
Labels: kind/feature, dco-signoff: yes, approved, size/XS, lgtm, needs-ok-to-test, area/plugins

#251 update(oci/CI): fetch tags using checkout action
  .github/workflows/upload-oci-artifacts.yaml
Labels: dco-signoff: yes, approved, size/XS, lgtm
