Repository falcosecurity/plugins, pull requests merged in 2024-07, with the labels that each got.

#517 fix(k8smeta): introduce /proc scan to recover the pod uid of threads already spawned
  plugins/k8smeta/README.md
  plugins/k8smeta/falco.yaml
  plugins/k8smeta/src/grpc_client.cpp
  plugins/k8smeta/src/plugin.cpp
  plugins/k8smeta/src/plugin.h
  plugins/k8smeta/src/shared_with_tests_consts.h
  plugins/k8smeta/test/README.md
  plugins/k8smeta/test/include/k8smeta_tests/helpers.h
  plugins/k8smeta/test/src/check_events.cpp
  plugins/k8smeta/test/src/init_config.cpp
  plugins/k8smeta/test/src/parsing_pod.cpp
Labels: kind/bug, kind/feature, dco-signoff: yes, approved, lgtm, size/XL, area/plugins

#520 Falco plugin for GitLab
  registry.yaml
Labels: kind/feature, dco-signoff: yes, approved, lgtm, size/S, area/plugins

#524 docs(README.md): update plugin registry table
  README.md
Labels: kind/documentation, dco-signoff: yes, approved, size/XS, lgtm, area/documentation
