Repository falcosecurity/plugins, pull requests merged in 2024-04, with the labels that each got.

#454 docs(k8saudit-gke): describe scaling options for high audit log volumes
  plugins/k8saudit-gke/README.md
Labels: kind/documentation, dco-signoff: yes, approved, size/XS, lgtm, area/documentation, area/plugins

#456 update(docs): update release docs
  release.md
Labels: kind/documentation, dco-signoff: yes, approved, lgtm, area/documentation, size/S

#457 fix(ci): support release of plugins with same prefix
  build/registry/pkg/oci/configLayer.go
  build/registry/pkg/oci/oci.go
  build/registry/pkg/oci/requirements.go
Labels: dco-signoff: yes, approved, lgtm, size/L

#461 update(registry.yaml): register journald plugin
  registry.yaml
Labels: kind/feature, dco-signoff: yes, approved, lgtm, size/S, area/registry

#462 docs(README.md): update plugin registry table
  README.md
Labels: kind/documentation, dco-signoff: yes, approved, size/XS, lgtm, area/documentation

#464 update(CI): change release tag format
  .github/workflows/release.yml
  build/utils/version.go
  release.md
Labels: dco-signoff: yes, approved, lgtm, size/S

#465 update(dummy): bump version for ci testing purpose
  plugins/dummy/pkg/dummy/dummy.go
Labels: dco-signoff: yes, approved, size/XS, lgtm

#466 fix(CI): extract info from plugin tag
  .github/workflows/release.yml
Labels: dco-signoff: yes, approved, size/XS, lgtm

#468 chore(k8saudit): bump version to 0.8.0 to release rule changes
  plugins/k8saudit/pkg/k8saudit/k8saudit.go
Labels: kind/bug, dco-signoff: yes, approved, size/XS, lgtm, area/plugins

#474 new(CI): add registry.yaml validator
  .github/workflows/registry.yaml
  build/registry/cmd/registry/registry.go
  build/registry/cmd/validateRegistry/validateRegistryFile.go
  build/registry/pkg/oci/const.go
  build/registry/pkg/oci/oci.go
Labels: dco-signoff: yes, approved, lgtm, size/L

#475 update(gcpaudit): bump version to 0.3.2
  plugins/gcpaudit/pkg/gcpaudit/gcpaudit.go
Labels: dco-signoff: yes, approved, size/XS, lgtm, area/plugins

#476 update(github): bump version to 0.7.3
  plugins/github/pkg/github/github.go
Labels: dco-signoff: yes, approved, size/XS, lgtm

#478 fix(ci): correctly retrieve plugin version from tag
  .github/get-latest-plugin-version.sh
Labels: kind/bug, dco-signoff: yes, approved, size/XS, lgtm

#477 fix(release/rules): ignore symlinks when releasing rulesfiles
  Makefile
Labels: kind/bug, dco-signoff: yes, approved, size/XS, lgtm

#480 fix(ci): correctly fetch repository head
  .github/workflows/reusable_suggest_rules_version.yaml
Labels: dco-signoff: yes, approved, size/XS, lgtm
