Repository falcosecurity/plugins, pull requests merged in 2024-03, with the labels that each got.

#422 feat(cloudtrail): Support for organization trails
  plugins/cloudtrail/pkg/cloudtrail/source.go
Labels: kind/feature, dco-signoff: yes, approved, size/XS, lgtm, area/plugins

#426 update the versions of falco and falcoctl in the CI
  .github/workflows/ci.yaml
  .github/workflows/master.yaml
  .github/workflows/release.yml
Labels: dco-signoff: yes, approved, lgtm, kind/cleanup, kind/failing-test, area/build, size/S

#432 fix(CI): correctly extract dependencies for alternatives plugins
  .github/extract-plugins-deps-from-rulesfile.sh
  .github/setup-plugin-config-rules.sh
  .github/workflows/reusable_suggest_rules_version.yaml
  .github/workflows/reusable_validate_plugins.yaml
Labels: dco-signoff: yes, approved, lgtm, size/L

#430 vote: add Issif as owner of the okta plugin for the PR approvals
  plugins/okta/OWNERS
Labels: dco-signoff: yes, approved, size/XS, lgtm, area/plugins

#429 refactor(cloudtrail): Get S3 keys concurrently
  plugins/cloudtrail/pkg/cloudtrail/source.go
Labels: dco-signoff: yes, approved, lgtm, kind/cleanup, size/L, area/plugins

#428 Fix application name extraction issue
  plugins/okta/CHANGELOG.md
  plugins/okta/README.md
  plugins/okta/pkg/okta/okta.go
  plugins/okta/rules/okta_rules.yaml
Labels: kind/bug, kind/documentation, dco-signoff: yes, approved, lgtm, area/documentation, size/S, area/plugins

#442 fix(CI): add suffix input to oci workflow
  .github/workflows/master.yaml
  .github/workflows/release.yml
  .github/workflows/reusable-publish-oci-artifacts.yaml
Labels: dco-signoff: yes, approved, size/XS, lgtm

#445 fix(CI): fix command in oci artifacts
  .github/workflows/reusable-publish-oci-artifacts.yaml
Labels: dco-signoff: yes, approved, size/XS, lgtm

#447 update(ci): update cosign version
  .github/workflows/reusable-publish-oci-artifacts.yaml
Labels: dco-signoff: yes, approved, size/XS, lgtm, kind/cleanup, area/build

#448 chore(dummy): bump version
  plugins/dummy/pkg/dummy/dummy.go
Labels: dco-signoff: yes, approved, size/XS, lgtm

#449 fix(oci): fix dependencies for publish-oci-artifacts workflow
  .github/workflows/release.yml
Labels: dco-signoff: yes, approved, size/XS, lgtm

#450 fix(ci): set empty string as a flag when not specified by the ci
  .github/workflows/reusable-publish-oci-artifacts.yaml
Labels: dco-signoff: yes, approved, size/XS, lgtm

#451 chore(github): bump version to 0.7.2
  plugins/github/pkg/github/github.go
Labels: dco-signoff: yes, approved, size/XS, lgtm

#453 chore(plugins): bump dummy plugin version
  plugins/dummy/pkg/dummy/dummy.go
Labels: dco-signoff: yes, approved, size/XS, lgtm, kind/cleanup, area/plugins

#452 docs(k8saudit-gke): Explain Pub/Sub setup alternatives
  plugins/k8saudit-gke/README.md
Labels: kind/documentation, dco-signoff: yes, approved, lgtm, area/documentation, size/S, area/plugins
